name: Test Documentation Examples
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.14
      - run: cabal install doctest
      - run: cabal repl --with-compiler=doctest
